version: "3.8"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
    env_file:
      - .env
