version: "3.8"

services:
  frontend:
    build: .
    container_name: react-frontend
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
